CREATE TABLE t_user(
	i_user INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	uid VARCHAR(10) UNIQUE NOT NULL,
	upw VARCHAR(15) NOT NULL,
	nick VARCHAR (10) NOT NULL,
	uphone VARCHAR(13) NOT NULL,
	gender INT UNSIGNED NOT NULL CHECK(gender IN(0,.1)),
	yy VARCHAR(4),
	mm VARCHAR(2),
	dd VARCHAR(2),
	addr VARCHAR(50),
	email VARCHAR(50),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP 
);

SELECT * FROM t_user;

CREATE TABLE t_board(
	i_board INT UNSIGNED AUTO_INCREMENT,
	PRIMARY KEY(i_board),
	title VARCHAR(100) NOT NULL,
	ctnt VARCHAR(2000) NOT NULL,
	i_user INT UNSIGNED NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(i_user) REFERENCES t_user(i_user)	
);
SELECT * FROM t_board;



